spring.application.name=LibraHub

# SQLite Database
spring.datasource.url=jdbc:sqlite:librahub.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Server
server.port=8080

# JWT
jwt.secret=librahub-secret-key-2024-make-it-long-enough-256bits-secure
jwt.expiration=86400000
